/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_mainWindow (void);
GtkWidget* create_URLAddDialog (void);
GtkWidget* create_FileSaveDialog (void);
GtkWidget* create_newConfirmDialog (void);
void cPigeGUIMessage(GtkWidget *mainWindow, gint type, gchar *message);
void InfoBox(GtkWidget *mainWindow, gchar *message);
void ErrorBox(GtkWidget *mainWindow, gchar *message);
void WarningBox(GtkWidget *mainWindow, gchar *message);
