/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>
#include <libintl.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_mainWindow (void)
{
  GtkWidget *mainWindow;
  GtkWidget *vbox1;
  GtkWidget *menubar1;
  GtkWidget *menuitem13;
  GtkWidget *menu13;
  GtkWidget *nouveau;
  GtkWidget *ouvrir;
  GtkWidget *enregistrer;
  GtkWidget *enregistrer_sous;
  GtkWidget *separatormenuitem1;
  GtkWidget *quitter;
  GtkWidget *vbox2;
  GtkWidget *ParametersFrame;
  GtkWidget *vbox6;
  GtkWidget *hbox9;
  GtkWidget *scrolledwindow1;
  GtkWidget *URLTreeView;
  GtkWidget *vbox7;
  GtkWidget *alignment8;
  GtkWidget *AddUrlBUtton;
  GtkWidget *alignment6;
  GtkWidget *addhbox;
  GtkWidget *image4;
  GtkWidget *label14;
  GtkWidget *DelURLButton;
  GtkWidget *alignment7;
  GtkWidget *hbox10;
  GtkWidget *image5;
  GtkWidget *label15;
  GtkWidget *alignment9;
  GtkWidget *table4;
  GtkWidget *SaveDirectoryLabel;
  GtkWidget *FileChooserButton;
  GtkWidget *LogfileCheckButton;
  GtkWidget *logfileChooseDialog;
  GtkWidget *LogfileChooserButton;
  GtkWidget *PigeModeFrame;
  GtkWidget *hbox11;
  GtkWidget *label17;
  GtkObject *IntervalDelaySpinButton_adj;
  GtkWidget *IntervalDelaySpinButton;
  GtkWidget *IntervalTypeComboBox;
  GtkWidget *label16;
  GtkWidget *MandatoryParametersLabel;
  GtkWidget *ExtraParametersFrame;
  GtkWidget *alignment2;
  GtkWidget *OnOffTable;
  GtkWidget *pigeModeButton;
  GtkWidget *WeekBackupButton;
  GtkWidget *pigeMetaButton;
  GtkWidget *quietModeButton;
  GtkWidget *backgroundButton;
  GtkWidget *useNumbersButton;
  GtkObject *spinbutton2_adj;
  GtkWidget *spinbutton2;
  GtkWidget *NextTitleEntry;
  GtkWidget *OnOffLabel;
  GtkWidget *frame4;
  GtkWidget *vbox3;
  GtkWidget *hbox3;
  GtkWidget *startButton;
  GtkWidget *alignment10;
  GtkWidget *hbox12;
  GtkWidget *startButtonImage;
  GtkWidget *startButtonLabel;
  GtkWidget *table3;
  GtkWidget *curSongLabel;
  GtkWidget *nextSongLabel;
  GtkWidget *titleEntry;
  GtkWidget *nexttitleEntry;
  GtkWidget *timeleftProgressBar;
  GtkWidget *label6;
  GtkWidget *log_table;
  GtkWidget *log_entry;
  GtkWidget *log_button;
  GtkWidget *log_align;
  GtkWidget *log_hbox;
  GtkWidget *log_image;
  GtkWidget *log_button_label;
  GtkAccelGroup *accel_group;
  GtkTooltips *tooltips;

  tooltips = gtk_tooltips_new ();

  accel_group = gtk_accel_group_new ();

  mainWindow = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_name (mainWindow, "mainWindow");
  gtk_window_set_title (GTK_WINDOW (mainWindow), gettext("cPige Configurator by Laurent Coustet"));
  gtk_window_set_icon_name (GTK_WINDOW (mainWindow), "gtk-media-record");

  vbox1 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox1, "vbox1");
  gtk_widget_show (vbox1);
  gtk_container_add (GTK_CONTAINER (mainWindow), vbox1);

  menubar1 = gtk_menu_bar_new ();
  gtk_widget_set_name (menubar1, "menubar1");
  gtk_widget_show (menubar1);
  gtk_box_pack_start (GTK_BOX (vbox1), menubar1, FALSE, FALSE, 0);

  menuitem13 = gtk_menu_item_new_with_mnemonic ("_Fichier");
  gtk_widget_set_name (menuitem13, "menuitem13");
  gtk_widget_show (menuitem13);
  gtk_container_add (GTK_CONTAINER (menubar1), menuitem13);

  menu13 = gtk_menu_new ();
  gtk_widget_set_name (menu13, "menu13");
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (menuitem13), menu13);

  nouveau = gtk_image_menu_item_new_from_stock ("gtk-new", accel_group);
  gtk_widget_set_name (nouveau, "nouveau");
  gtk_widget_show (nouveau);
  gtk_container_add (GTK_CONTAINER (menu13), nouveau);

  ouvrir = gtk_image_menu_item_new_from_stock ("gtk-open", accel_group);
  gtk_widget_set_name (ouvrir, "ouvrir");
  gtk_widget_show (ouvrir);
  gtk_container_add (GTK_CONTAINER (menu13), ouvrir);

  enregistrer = gtk_image_menu_item_new_from_stock ("gtk-save", accel_group);
  gtk_widget_set_name (enregistrer, "enregistrer");
  gtk_widget_show (enregistrer);
  gtk_container_add (GTK_CONTAINER (menu13), enregistrer);

  enregistrer_sous = gtk_image_menu_item_new_from_stock ("gtk-save-as", accel_group);
  gtk_widget_set_name (enregistrer_sous, "enregistrer_sous");
  gtk_widget_show (enregistrer_sous);
  gtk_container_add (GTK_CONTAINER (menu13), enregistrer_sous);

  separatormenuitem1 = gtk_separator_menu_item_new ();
  gtk_widget_set_name (separatormenuitem1, "separatormenuitem1");
  gtk_widget_show (separatormenuitem1);
  gtk_container_add (GTK_CONTAINER (menu13), separatormenuitem1);
  gtk_widget_set_sensitive (separatormenuitem1, FALSE);

  quitter = gtk_image_menu_item_new_from_stock ("gtk-quit", accel_group);
  gtk_widget_set_name (quitter, "quitter");
  gtk_widget_show (quitter);
  gtk_container_add (GTK_CONTAINER (menu13), quitter);

  vbox2 = gtk_vbox_new (FALSE, 7);
  gtk_widget_set_name (vbox2, "vbox2");
  gtk_widget_show (vbox2);
  gtk_box_pack_start (GTK_BOX (vbox1), vbox2, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (vbox2), 10);

  ParametersFrame = gtk_frame_new (NULL);
  gtk_widget_set_name (ParametersFrame, "ParametersFrame");
  gtk_widget_show (ParametersFrame);
  gtk_box_pack_start (GTK_BOX (vbox2), ParametersFrame, TRUE, TRUE, 0);
  gtk_frame_set_shadow_type (GTK_FRAME (ParametersFrame), GTK_SHADOW_IN);

  vbox6 = gtk_vbox_new (FALSE, 6);
  gtk_widget_set_name (vbox6, "vbox6");
  gtk_widget_show (vbox6);
  gtk_container_add (GTK_CONTAINER (ParametersFrame), vbox6);
  gtk_container_set_border_width (GTK_CONTAINER (vbox6), 4);

  hbox9 = gtk_hbox_new (FALSE, 5);
  gtk_widget_set_name (hbox9, "hbox9");
  gtk_widget_show (hbox9);
  gtk_box_pack_start (GTK_BOX (vbox6), hbox9, TRUE, TRUE, 0);

  scrolledwindow1 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_set_name (scrolledwindow1, "scrolledwindow1");
  gtk_widget_show (scrolledwindow1);
  gtk_box_pack_start (GTK_BOX (hbox9), scrolledwindow1, TRUE, TRUE, 0);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow1), GTK_POLICY_NEVER, GTK_POLICY_AUTOMATIC);
  gtk_scrolled_window_set_shadow_type (GTK_SCROLLED_WINDOW (scrolledwindow1), GTK_SHADOW_IN);

  URLTreeView = gtk_tree_view_new ();
  gtk_widget_set_name (URLTreeView, "URLTreeView");
  gtk_widget_show (URLTreeView);
  gtk_container_add (GTK_CONTAINER (scrolledwindow1), URLTreeView);

  vbox7 = gtk_vbox_new (FALSE, 4);
  gtk_widget_set_name (vbox7, "vbox7");
  gtk_widget_show (vbox7);
  gtk_box_pack_start (GTK_BOX (hbox9), vbox7, FALSE, FALSE, 0);

  alignment8 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_set_name (alignment8, "alignment8");
  gtk_widget_show (alignment8);
  gtk_box_pack_start (GTK_BOX (vbox7), alignment8, TRUE, TRUE, 0);

  AddUrlBUtton = gtk_button_new ();
  gtk_widget_set_name (AddUrlBUtton, "AddUrlBUtton");
  gtk_widget_show (AddUrlBUtton);
  gtk_box_pack_start (GTK_BOX (vbox7), AddUrlBUtton, FALSE, FALSE, 0);
  gtk_tooltips_set_tip (tooltips, AddUrlBUtton, gettext("Add an URL to the pool."), NULL);
  gtk_button_set_focus_on_click (GTK_BUTTON (AddUrlBUtton), FALSE);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_set_name (alignment6, "alignment6");
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (AddUrlBUtton), alignment6);

  addhbox = gtk_hbox_new (FALSE, 2);
  gtk_widget_set_name (addhbox, "addhbox");
  gtk_widget_show (addhbox);
  gtk_container_add (GTK_CONTAINER (alignment6), addhbox);

  image4 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_set_name (image4, "image4");
  gtk_widget_show (image4);
  gtk_box_pack_start (GTK_BOX (addhbox), image4, FALSE, FALSE, 0);

  label14 = gtk_label_new_with_mnemonic (gettext("Add"));
  gtk_widget_set_name (label14, "label14");
  gtk_widget_show (label14);
  gtk_box_pack_start (GTK_BOX (addhbox), label14, FALSE, FALSE, 0);

  DelURLButton = gtk_button_new ();
  gtk_widget_set_name (DelURLButton, "DelURLButton");
  gtk_widget_show (DelURLButton);
  gtk_box_pack_start (GTK_BOX (vbox7), DelURLButton, FALSE, FALSE, 0);
  gtk_tooltips_set_tip (tooltips, DelURLButton, gettext("Remove an URL from the pool."), NULL);
  gtk_button_set_focus_on_click (GTK_BUTTON (DelURLButton), FALSE);

  alignment7 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_set_name (alignment7, "alignment7");
  gtk_widget_show (alignment7);
  gtk_container_add (GTK_CONTAINER (DelURLButton), alignment7);

  hbox10 = gtk_hbox_new (FALSE, 2);
  gtk_widget_set_name (hbox10, "hbox10");
  gtk_widget_show (hbox10);
  gtk_container_add (GTK_CONTAINER (alignment7), hbox10);

  image5 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_set_name (image5, "image5");
  gtk_widget_show (image5);
  gtk_box_pack_start (GTK_BOX (hbox10), image5, FALSE, FALSE, 0);

  label15 = gtk_label_new_with_mnemonic (gettext("Del"));
  gtk_widget_set_name (label15, "label15");
  gtk_widget_show (label15);
  gtk_box_pack_start (GTK_BOX (hbox10), label15, FALSE, FALSE, 0);

  alignment9 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_set_name (alignment9, "alignment9");
  gtk_widget_show (alignment9);
  gtk_box_pack_start (GTK_BOX (vbox7), alignment9, TRUE, TRUE, 0);

  table4 = gtk_table_new (2, 2, FALSE);
  gtk_widget_set_name (table4, "table4");
  gtk_widget_show (table4);
  gtk_box_pack_start (GTK_BOX (vbox6), table4, FALSE, FALSE, 0);
  gtk_table_set_row_spacings (GTK_TABLE (table4), 3);
  gtk_table_set_col_spacings (GTK_TABLE (table4), 18);

  SaveDirectoryLabel = gtk_label_new (gettext("Save directory"));
  gtk_widget_set_name (SaveDirectoryLabel, "SaveDirectoryLabel");
  gtk_widget_show (SaveDirectoryLabel);
  gtk_table_attach (GTK_TABLE (table4), SaveDirectoryLabel, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  FileChooserButton = gtk_file_chooser_button_new (gettext("File selection"), GTK_FILE_CHOOSER_ACTION_SELECT_FOLDER);
  gtk_widget_set_name (FileChooserButton, "FileChooserButton");
  gtk_widget_show (FileChooserButton);
  gtk_table_attach (GTK_TABLE (table4), FileChooserButton, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  LogfileCheckButton = gtk_check_button_new_with_mnemonic ("Logfile");
  gtk_widget_set_name (LogfileCheckButton, "LogfileCheckButton");
  gtk_widget_show (LogfileCheckButton);
  gtk_table_attach (GTK_TABLE (table4), LogfileCheckButton, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_tooltips_set_tip (tooltips, LogfileCheckButton, gettext("Do you want cPige to store his action in a logfile ?"), NULL);
  gtk_button_set_focus_on_click (GTK_BUTTON (LogfileCheckButton), FALSE);
  gtk_toggle_button_set_active (GTK_TOGGLE_BUTTON (LogfileCheckButton), TRUE);

  log_table = gtk_hbox_new (FALSE, 4);
  gtk_widget_show (log_table);

  log_entry = gtk_entry_new ();
  gtk_widget_set_name(log_entry, "LogfileEntry");
  gtk_widget_show (log_entry);
  gtk_box_pack_start (GTK_BOX (log_table), log_entry, TRUE, TRUE, 0);

  log_button = gtk_button_new ();
  gtk_widget_show (log_button);
  gtk_widget_set_name (log_button, "LogfileChooserButton");
  gtk_box_pack_start (GTK_BOX (log_table), log_button, FALSE, FALSE, 0);

  log_align = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (log_align);
  gtk_container_add (GTK_CONTAINER (log_button), log_align);

  log_hbox = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (log_hbox);
  gtk_container_add (GTK_CONTAINER (log_align), log_hbox);

  log_image = gtk_image_new_from_stock ("gtk-open", GTK_ICON_SIZE_SMALL_TOOLBAR);
  gtk_widget_show (log_image);
  gtk_box_pack_start (GTK_BOX (log_hbox), log_image, FALSE, FALSE, 0);

  log_button_label = gtk_label_new_with_mnemonic (gettext("Open"));
  gtk_widget_show (log_button_label);
  gtk_box_pack_start (GTK_BOX (log_hbox), log_button_label, FALSE, FALSE, 0);

  gtk_table_attach (GTK_TABLE (table4), log_table, 1, 2, 1, 2, 
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  PigeModeFrame = gtk_frame_new (NULL);
  gtk_widget_set_name (PigeModeFrame, "PigeModeFrame");
  gtk_widget_show (PigeModeFrame);
  gtk_box_pack_start (GTK_BOX (vbox6), PigeModeFrame, FALSE, TRUE, 0);
  gtk_frame_set_shadow_type (GTK_FRAME (PigeModeFrame), GTK_SHADOW_IN);

  hbox11 = gtk_hbox_new (FALSE, 8);
  gtk_widget_set_name (hbox11, "hbox11");
  gtk_widget_show (hbox11);
  gtk_container_add (GTK_CONTAINER (PigeModeFrame), hbox11);
  gtk_container_set_border_width (GTK_CONTAINER (hbox11), 3);

  label17 = gtk_label_new (gettext("Split files every"));
  gtk_widget_set_name (label17, "label17");
  gtk_widget_show (label17);
  gtk_box_pack_start (GTK_BOX (hbox11), label17, FALSE, FALSE, 0);

  IntervalDelaySpinButton_adj = gtk_adjustment_new (10, 10, 30, 10, 10, 10);
  IntervalDelaySpinButton = gtk_spin_button_new (GTK_ADJUSTMENT (IntervalDelaySpinButton_adj), 1, 0);
  gtk_widget_set_name (IntervalDelaySpinButton, "IntervalDelaySpinButton");
  gtk_widget_show (IntervalDelaySpinButton);
  gtk_box_pack_start (GTK_BOX (hbox11), IntervalDelaySpinButton, FALSE, TRUE, 0);
  gtk_tooltips_set_tip (tooltips, IntervalDelaySpinButton, gettext("Each n \"Hour\" or \"Minutes\", cPige will create a new file."), NULL);
  gtk_spin_button_set_numeric (GTK_SPIN_BUTTON (IntervalDelaySpinButton), TRUE);

  IntervalTypeComboBox = gtk_combo_box_new_text ();
  gtk_widget_set_name (IntervalTypeComboBox, "IntervalTypeComboBox");
  gtk_widget_show (IntervalTypeComboBox);
  gtk_box_pack_start (GTK_BOX (hbox11), IntervalTypeComboBox, TRUE, TRUE, 0);
  gtk_combo_box_append_text (GTK_COMBO_BOX (IntervalTypeComboBox), gettext("Hour(s)"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (IntervalTypeComboBox), gettext("Minutes"));

  label16 = gtk_label_new (gettext("<b>Pige mode only</b>"));
  gtk_widget_set_name (label16, "label16");
  gtk_widget_show (label16);
  gtk_frame_set_label_widget (GTK_FRAME (PigeModeFrame), label16);
  gtk_label_set_use_markup (GTK_LABEL (label16), TRUE);

  MandatoryParametersLabel = gtk_label_new (gettext("<b>Mandatory parameters</b>"));
  gtk_widget_set_name (MandatoryParametersLabel, "MandatoryParametersLabel");
  gtk_widget_show (MandatoryParametersLabel);
  gtk_frame_set_label_widget (GTK_FRAME (ParametersFrame), MandatoryParametersLabel);
  gtk_label_set_use_markup (GTK_LABEL (MandatoryParametersLabel), TRUE);

  ExtraParametersFrame = gtk_frame_new (NULL);
  gtk_widget_set_name (ExtraParametersFrame, "ExtraParametersFrame");
  gtk_widget_show (ExtraParametersFrame);
  gtk_box_pack_start (GTK_BOX (vbox2), ExtraParametersFrame, FALSE, TRUE, 0);
  gtk_frame_set_shadow_type (GTK_FRAME (ExtraParametersFrame), GTK_SHADOW_IN);

  alignment2 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_set_name (alignment2, "alignment2");
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (ExtraParametersFrame), alignment2);

  OnOffTable = gtk_table_new (2, 4, FALSE);
  gtk_widget_set_name (OnOffTable, "OnOffTable");
  gtk_widget_show (OnOffTable);
  gtk_container_add (GTK_CONTAINER (alignment2), OnOffTable);
  gtk_container_set_border_width (GTK_CONTAINER (OnOffTable), 6);
  gtk_table_set_row_spacings (GTK_TABLE (OnOffTable), 3);
  gtk_table_set_col_spacings (GTK_TABLE (OnOffTable), 6);

  pigeModeButton = gtk_check_button_new_with_mnemonic (gettext("pige mode"));
  gtk_widget_set_name (pigeModeButton, "pigeModeButton");
  gtk_widget_show (pigeModeButton);
  gtk_table_attach (GTK_TABLE (OnOffTable), pigeModeButton, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_tooltips_set_tip (tooltips, pigeModeButton, gettext("Do you want cPige to archive the stream in Pige mode?\nIn pige mode, cPige will cut the stream using a time base."), NULL);
  gtk_button_set_focus_on_click (GTK_BUTTON (pigeModeButton), FALSE);
  gtk_toggle_button_set_active (GTK_TOGGLE_BUTTON (pigeModeButton), TRUE);

  WeekBackupButton = gtk_check_button_new_with_mnemonic (gettext("week backup"));
  gtk_widget_set_name (WeekBackupButton, "WeekBackupButton");
  gtk_widget_show (WeekBackupButton);
  gtk_table_attach (GTK_TABLE (OnOffTable), WeekBackupButton, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_tooltips_set_tip (tooltips, WeekBackupButton, gettext("Do you want cPige to archive a complete week of streaming?"), NULL);
  gtk_button_set_focus_on_click (GTK_BUTTON (WeekBackupButton), FALSE);

  pigeMetaButton = gtk_check_button_new_with_mnemonic (gettext("pige meta"));
  gtk_widget_set_name (pigeMetaButton, "pigeMetaButton");
  gtk_widget_show (pigeMetaButton);
  gtk_table_attach (GTK_TABLE (OnOffTable), pigeMetaButton, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_tooltips_set_tip (tooltips, pigeMetaButton, gettext("Do you want cPige to add ID3 tags to your piged files (Only available using pige mode)"), NULL);
  gtk_button_set_focus_on_click (GTK_BUTTON (pigeMetaButton), FALSE);

  quietModeButton = gtk_check_button_new_with_mnemonic (gettext("quiet mode"));
  gtk_widget_set_name (quietModeButton, "quietModeButton");
  gtk_widget_show (quietModeButton);
  gtk_table_attach (GTK_TABLE (OnOffTable), quietModeButton, 2, 3, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_tooltips_set_tip (tooltips, quietModeButton, gettext("Do you want cPige to gives you the status of the stream grabbing ? Like the title of the song played, the time cPige is running, and so on.\n\nNote that this parameter is useless starting cPige with the GUI."), NULL);
  gtk_button_set_relief (GTK_BUTTON (quietModeButton), GTK_RELIEF_NONE);
  gtk_button_set_focus_on_click (GTK_BUTTON (quietModeButton), FALSE);

  backgroundButton = gtk_check_button_new_with_mnemonic (gettext("background"));
  gtk_widget_set_name (backgroundButton, "backgroundButton");
  gtk_widget_show (backgroundButton);
  gtk_table_attach (GTK_TABLE (OnOffTable), backgroundButton, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_tooltips_set_tip (tooltips, backgroundButton, gettext("Do you want to run cPige in background mode. <b>This option is currently ONLY available under UNIX systems.</b>"), NULL);
  gtk_button_set_focus_on_click (GTK_BUTTON (backgroundButton), FALSE);

  useNumbersButton = gtk_check_button_new_with_mnemonic (gettext("use numbers"));
  gtk_widget_set_name (useNumbersButton, "useNumbersButton");
  gtk_widget_show (useNumbersButton);
  gtk_table_attach (GTK_TABLE (OnOffTable), useNumbersButton, 2, 3, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_sensitive (useNumbersButton, FALSE);
  gtk_tooltips_set_tip (tooltips, useNumbersButton, gettext("Should cPige prefix songs with a unique number ? (UNIX only, with pige mode Disabled)"), NULL);
  gtk_button_set_focus_on_click (GTK_BUTTON (useNumbersButton), FALSE);

  spinbutton2_adj = gtk_adjustment_new (0, 0, 100, 1, 10, 10);
  spinbutton2 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton2_adj), 1, 0);
  gtk_widget_set_name (spinbutton2, "skipSongsSpin");
  gtk_widget_show (spinbutton2);
  gtk_table_attach (GTK_TABLE (OnOffTable), spinbutton2, 3, 4, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_tooltips_set_tip (tooltips, spinbutton2, gettext("How many songs cPige should skip before starting recording"), NULL);
  gtk_spin_button_set_numeric (GTK_SPIN_BUTTON (spinbutton2), TRUE);

  NextTitleEntry = gtk_entry_new ();
  gtk_widget_set_name (NextTitleEntry, "NextTitleEntry");
  gtk_widget_show (NextTitleEntry);
  gtk_table_attach (GTK_TABLE (OnOffTable), NextTitleEntry, 3, 4, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_tooltips_set_tip (tooltips, NextTitleEntry, gettext("This entry is used by cPige to detect if the new title sent by the webradio is a \"next title\" information, or a real new title."), NULL);
  gtk_entry_set_text (GTK_ENTRY (NextTitleEntry), "Next Title");

  OnOffLabel = gtk_label_new (gettext("<b>Extra Parameters</b>"));
  gtk_widget_set_name (OnOffLabel, "OnOffLabel");
  gtk_widget_show (OnOffLabel);
  gtk_frame_set_label_widget (GTK_FRAME (ExtraParametersFrame), OnOffLabel);
  gtk_label_set_use_markup (GTK_LABEL (OnOffLabel), TRUE);

  frame4 = gtk_frame_new (NULL);
  gtk_widget_set_name (frame4, "frame4");
  gtk_widget_show (frame4);
  gtk_box_pack_start (GTK_BOX (vbox2), frame4, FALSE, TRUE, 0);
  gtk_frame_set_shadow_type (GTK_FRAME (frame4), GTK_SHADOW_IN);

  vbox3 = gtk_vbox_new (FALSE, 6);
  gtk_widget_set_name (vbox3, "vbox3");
  gtk_widget_show (vbox3);
  gtk_container_add (GTK_CONTAINER (frame4), vbox3);
  gtk_container_set_border_width (GTK_CONTAINER (vbox3), 5);

  hbox3 = gtk_hbox_new (FALSE, 6);
  gtk_widget_set_name (hbox3, "hbox3");
  gtk_widget_show (hbox3);
  gtk_box_pack_start (GTK_BOX (vbox3), hbox3, FALSE, TRUE, 0);

  startButton = gtk_toggle_button_new ();
  gtk_widget_set_name (startButton, "startButton");
  gtk_widget_show (startButton);
  gtk_box_pack_start (GTK_BOX (hbox3), startButton, FALSE, FALSE, 0);
  GTK_WIDGET_SET_FLAGS (startButton, GTK_CAN_DEFAULT);
  gtk_tooltips_set_tip (tooltips, startButton, gettext("This button is used to start / stop cPige recording"), NULL);
  gtk_button_set_focus_on_click (GTK_BUTTON (startButton), FALSE);
  g_object_set_data(G_OBJECT(startButton), "savemode", FALSE);

  alignment10 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_set_name (alignment10, "alignment10");
  gtk_widget_show (alignment10);
  gtk_container_add (GTK_CONTAINER (startButton), alignment10);

  hbox12 = gtk_hbox_new (FALSE, 2);
  gtk_widget_set_name (hbox12, "hbox12");
  gtk_widget_show (hbox12);
  gtk_container_add (GTK_CONTAINER (alignment10), hbox12);

  startButtonImage = gtk_image_new_from_stock ("gtk-media-play", GTK_ICON_SIZE_BUTTON);
  gtk_widget_set_name (startButtonImage, "startButtonImage");
  gtk_widget_show (startButtonImage);
  gtk_box_pack_start (GTK_BOX (hbox12), startButtonImage, FALSE, FALSE, 0);

  startButtonLabel = gtk_label_new_with_mnemonic (gettext("Start"));
  gtk_widget_set_name (startButtonLabel, "startButtonLabel");
  gtk_widget_show (startButtonLabel);
  gtk_box_pack_start (GTK_BOX (hbox12), startButtonLabel, FALSE, FALSE, 0);

  table3 = gtk_table_new (2, 2, FALSE);
  gtk_widget_set_name (table3, "table3");
  gtk_widget_show (table3);
  gtk_box_pack_start (GTK_BOX (hbox3), table3, TRUE, TRUE, 0);
  gtk_table_set_row_spacings (GTK_TABLE (table3), 2);
  gtk_table_set_col_spacings (GTK_TABLE (table3), 9);

  curSongLabel = gtk_label_new (gettext("Current song"));
  gtk_widget_set_name (curSongLabel, "curSongLabel");
  gtk_widget_show (curSongLabel);
  gtk_table_attach (GTK_TABLE (table3), curSongLabel, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (curSongLabel), 0, 0.5);

  nextSongLabel = gtk_label_new (gettext("Next song"));
  gtk_widget_set_name (nextSongLabel, "nextSongLabel");
  gtk_widget_show (nextSongLabel);
  gtk_table_attach (GTK_TABLE (table3), nextSongLabel, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (nextSongLabel), 0, 0.5);

  titleEntry = gtk_entry_new ();
  gtk_widget_set_name (titleEntry, "titleEntry");
  gtk_widget_show (titleEntry);
  gtk_table_attach (GTK_TABLE (table3), titleEntry, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_sensitive (titleEntry, FALSE);
  GTK_WIDGET_UNSET_FLAGS (titleEntry, GTK_CAN_FOCUS);
  gtk_tooltips_set_tip (tooltips, titleEntry, gettext("This is the title of the song currently recording"), NULL);
  gtk_editable_set_editable (GTK_EDITABLE (titleEntry), FALSE);

  nexttitleEntry = gtk_entry_new ();
  gtk_widget_set_name (nexttitleEntry, "nexttitleEntry");
  gtk_widget_show (nexttitleEntry);
  gtk_table_attach (GTK_TABLE (table3), nexttitleEntry, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_widget_set_sensitive (nexttitleEntry, FALSE);
  GTK_WIDGET_UNSET_FLAGS (nexttitleEntry, GTK_CAN_FOCUS);
  gtk_tooltips_set_tip (tooltips, nexttitleEntry, gettext("This is the title of the next song we are going to record."), NULL);
  gtk_editable_set_editable (GTK_EDITABLE (nexttitleEntry), FALSE);

  timeleftProgressBar = gtk_progress_bar_new ();
  gtk_progress_bar_set_pulse_step(GTK_PROGRESS_BAR(timeleftProgressBar), 0.5);
  gtk_widget_set_name (timeleftProgressBar, "timeleftProgressBar");
  gtk_widget_show (timeleftProgressBar);
  gtk_box_pack_start (GTK_BOX (vbox3), timeleftProgressBar, FALSE, FALSE, 0);
  gtk_progress_bar_set_pulse_step (GTK_PROGRESS_BAR (timeleftProgressBar), 0.01);
  gtk_progress_bar_set_text (GTK_PROGRESS_BAR (timeleftProgressBar), gettext("timeleft"));

  label6 = gtk_label_new (gettext("<b>Stream status</b>"));
  gtk_widget_set_name (label6, "label6");
  gtk_widget_show (label6);
  gtk_frame_set_label_widget (GTK_FRAME (frame4), label6);
  gtk_label_set_use_markup (GTK_LABEL (label6), TRUE);

  g_signal_connect ((gpointer) mainWindow, "destroy",
                    G_CALLBACK (on_quitter_activate),
                    NULL);
  g_signal_connect ((gpointer) nouveau, "activate",
                    G_CALLBACK (on_nouveau_activate),
                    NULL);
  g_signal_connect ((gpointer) ouvrir, "activate",
                    G_CALLBACK (on_ouvrir_activate),
                    NULL);
  g_signal_connect ((gpointer) enregistrer, "activate",
                    G_CALLBACK (on_enregistrer_activate),
                    NULL);
  g_signal_connect ((gpointer) enregistrer_sous, "activate",
                    G_CALLBACK (on_enregistrer_sous_activate),
                    NULL);
  g_signal_connect ((gpointer) quitter, "activate",
                    G_CALLBACK (on_quitter_activate),
                    NULL);
  g_signal_connect ((gpointer) AddUrlBUtton, "pressed",
                    G_CALLBACK (on_AddUrlBUtton_pressed),
                    NULL);
  g_signal_connect ((gpointer) DelURLButton, "pressed",
                    G_CALLBACK (on_DelURLButton_pressed),
                    NULL);
  g_signal_connect ((gpointer) LogfileCheckButton, "toggled",
                    G_CALLBACK (on_LogfileCheckButton_pressed),
                    NULL);
  g_signal_connect ((gpointer) IntervalTypeComboBox, "changed",
                    G_CALLBACK (on_IntervalTypeComboBox_changed),
                    NULL);
  g_signal_connect ((gpointer) pigeModeButton, "toggled",
                    G_CALLBACK (on_pigeModeButton_pressed),
                    NULL);
  g_signal_connect ((gpointer) startButton, "clicked",
                    G_CALLBACK (on_startButton_clicked),
                    NULL);
  g_signal_connect ((gpointer) log_button, "pressed",
                    G_CALLBACK (on_log_open_pressed),
                    NULL);
  g_signal_connect ((gpointer) FileChooserButton, "selection-changed",
                    G_CALLBACK (something_changed),
                    NULL);

  /* Connects each button to a function that will known
   * if something has changed in the configuration,
   * and if the configuration should be saved, or not
   */
  gpointer buttons[] = {
                        pigeModeButton, WeekBackupButton,     /* Classic buttons */
                        pigeMetaButton, quietModeButton, 
                        backgroundButton, useNumbersButton,
                        LogfileCheckButton,
                        NULL,
                        IntervalDelaySpinButton, spinbutton2, /* Spin buttons */
                        NULL,
                        IntervalTypeComboBox,                 /* combo & textbox */
                        NextTitleEntry,
                        log_entry,
                        NULL
                      };
  gint iter = 0;
  
  /* Traitement des boutons */
  while (buttons[iter] != NULL)
    g_signal_connect((gpointer) buttons[iter++], "pressed",
                     G_CALLBACK (something_changed),
                     NULL);
  iter++;

  /* Traitement des spin button */
  while (buttons[iter] != NULL)
    g_signal_connect ((gpointer) buttons[iter++] , "value_changed",
                      G_CALLBACK (something_changed),
                      NULL);

  iter++;

  /* Traitement des combo + champs texte */
  while (buttons[iter] != NULL)
    g_signal_connect ((gpointer) buttons[iter++] , "changed",
                      G_CALLBACK (something_changed),
                      NULL);
  
  
  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (mainWindow, mainWindow, "mainWindow");
  GLADE_HOOKUP_OBJECT (mainWindow, vbox1, "vbox1");
  GLADE_HOOKUP_OBJECT (mainWindow, menubar1, "menubar1");
  GLADE_HOOKUP_OBJECT (mainWindow, menuitem13, "menuitem13");
  GLADE_HOOKUP_OBJECT (mainWindow, menu13, "menu13");
  GLADE_HOOKUP_OBJECT (mainWindow, nouveau, "nouveau");
  GLADE_HOOKUP_OBJECT (mainWindow, ouvrir, "ouvrir");
  GLADE_HOOKUP_OBJECT (mainWindow, enregistrer, "enregistrer");
  GLADE_HOOKUP_OBJECT (mainWindow, enregistrer_sous, "enregistrer_sous");
  GLADE_HOOKUP_OBJECT (mainWindow, separatormenuitem1, "separatormenuitem1");
  GLADE_HOOKUP_OBJECT (mainWindow, quitter, "quitter");
  GLADE_HOOKUP_OBJECT (mainWindow, vbox2, "vbox2");
  GLADE_HOOKUP_OBJECT (mainWindow, ParametersFrame, "ParametersFrame");
  GLADE_HOOKUP_OBJECT (mainWindow, vbox6, "vbox6");
  GLADE_HOOKUP_OBJECT (mainWindow, hbox9, "hbox9");
  GLADE_HOOKUP_OBJECT (mainWindow, scrolledwindow1, "scrolledwindow1");
  GLADE_HOOKUP_OBJECT (mainWindow, URLTreeView, "URLTreeView");
  GLADE_HOOKUP_OBJECT (mainWindow, vbox7, "vbox7");
  GLADE_HOOKUP_OBJECT (mainWindow, alignment8, "alignment8");
  GLADE_HOOKUP_OBJECT (mainWindow, AddUrlBUtton, "AddUrlBUtton");
  GLADE_HOOKUP_OBJECT (mainWindow, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (mainWindow, addhbox, "addhbox");
  GLADE_HOOKUP_OBJECT (mainWindow, image4, "image4");
  GLADE_HOOKUP_OBJECT (mainWindow, label14, "label14");
  GLADE_HOOKUP_OBJECT (mainWindow, DelURLButton, "DelURLButton");
  GLADE_HOOKUP_OBJECT (mainWindow, alignment7, "alignment7");
  GLADE_HOOKUP_OBJECT (mainWindow, hbox10, "hbox10");
  GLADE_HOOKUP_OBJECT (mainWindow, image5, "image5");
  GLADE_HOOKUP_OBJECT (mainWindow, label15, "label15");
  GLADE_HOOKUP_OBJECT (mainWindow, alignment9, "alignment9");
  GLADE_HOOKUP_OBJECT (mainWindow, table4, "table4");
  GLADE_HOOKUP_OBJECT (mainWindow, SaveDirectoryLabel, "SaveDirectoryLabel");
  GLADE_HOOKUP_OBJECT (mainWindow, FileChooserButton, "FileChooserButton");
  GLADE_HOOKUP_OBJECT (mainWindow, LogfileCheckButton, "LogfileCheckButton");
  GLADE_HOOKUP_OBJECT (mainWindow, log_button, "LogfileChooserButton");
  GLADE_HOOKUP_OBJECT (mainWindow, log_entry, "LogfileEntry");
  GLADE_HOOKUP_OBJECT (mainWindow, PigeModeFrame, "PigeModeFrame");
  GLADE_HOOKUP_OBJECT (mainWindow, hbox11, "hbox11");
  GLADE_HOOKUP_OBJECT (mainWindow, label17, "label17");
  GLADE_HOOKUP_OBJECT (mainWindow, IntervalDelaySpinButton, "IntervalDelaySpinButton");
  GLADE_HOOKUP_OBJECT (mainWindow, IntervalTypeComboBox, "IntervalTypeComboBox");
  GLADE_HOOKUP_OBJECT (mainWindow, label16, "label16");
  GLADE_HOOKUP_OBJECT (mainWindow, MandatoryParametersLabel, "MandatoryParametersLabel");
  GLADE_HOOKUP_OBJECT (mainWindow, ExtraParametersFrame, "ExtraParametersFrame");
  GLADE_HOOKUP_OBJECT (mainWindow, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (mainWindow, OnOffTable, "OnOffTable");
  GLADE_HOOKUP_OBJECT (mainWindow, pigeModeButton, "pigeModeButton");
  GLADE_HOOKUP_OBJECT (mainWindow, WeekBackupButton, "WeekBackupButton");
  GLADE_HOOKUP_OBJECT (mainWindow, pigeMetaButton, "pigeMetaButton");
  GLADE_HOOKUP_OBJECT (mainWindow, quietModeButton, "quietModeButton");
  GLADE_HOOKUP_OBJECT (mainWindow, backgroundButton, "backgroundButton");
  GLADE_HOOKUP_OBJECT (mainWindow, useNumbersButton, "useNumbersButton");
  GLADE_HOOKUP_OBJECT (mainWindow, spinbutton2, "skipSongsSpin");
  GLADE_HOOKUP_OBJECT (mainWindow, NextTitleEntry, "NextTitleEntry");
  GLADE_HOOKUP_OBJECT (mainWindow, OnOffLabel, "OnOffLabel");
  GLADE_HOOKUP_OBJECT (mainWindow, frame4, "frame4");
  GLADE_HOOKUP_OBJECT (mainWindow, vbox3, "vbox3");
  GLADE_HOOKUP_OBJECT (mainWindow, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (mainWindow, startButton, "startButton");
  GLADE_HOOKUP_OBJECT (mainWindow, alignment10, "alignment10");
  GLADE_HOOKUP_OBJECT (mainWindow, hbox12, "hbox12");
  GLADE_HOOKUP_OBJECT (mainWindow, startButtonImage, "startButtonImage");
  GLADE_HOOKUP_OBJECT (mainWindow, startButtonLabel, "startButtonLabel");
  GLADE_HOOKUP_OBJECT (mainWindow, table3, "table3");
  GLADE_HOOKUP_OBJECT (mainWindow, curSongLabel, "curSongLabel");
  GLADE_HOOKUP_OBJECT (mainWindow, nextSongLabel, "nextSongLabel");
  GLADE_HOOKUP_OBJECT (mainWindow, titleEntry, "titleEntry");
  GLADE_HOOKUP_OBJECT (mainWindow, nexttitleEntry, "nexttitleEntry");
  GLADE_HOOKUP_OBJECT (mainWindow, timeleftProgressBar, "timeleftProgressBar");
  GLADE_HOOKUP_OBJECT (mainWindow, label6, "label6");
  GLADE_HOOKUP_OBJECT_NO_REF (mainWindow, tooltips, "tooltips");

  gtk_widget_grab_default (startButton);
  gtk_window_add_accel_group (GTK_WINDOW (mainWindow), accel_group);

  return mainWindow;
}

GtkWidget*
create_URLAddDialog (void)
{
  GtkWidget *URLAddDialog;
  GtkWidget *dialog_vbox1;
  GtkWidget *vbox8;
  GtkWidget *urlLabel;
  GtkWidget *URLAddEntry;
  GtkWidget *dialog_action_area1;
  GtkWidget *cancelbutton1;
  GtkWidget *okbutton1;
  GtkTooltips *tooltips;

  tooltips = gtk_tooltips_new ();

  URLAddDialog = gtk_dialog_new ();
  gtk_widget_set_name (URLAddDialog, "URLAddDialog");
  gtk_window_set_title (GTK_WINDOW (URLAddDialog), gettext("Add an URL"));
  gtk_window_set_position (GTK_WINDOW (URLAddDialog), GTK_WIN_POS_CENTER);
  gtk_window_set_modal (GTK_WINDOW (URLAddDialog), TRUE);
  gtk_window_set_icon_name (GTK_WINDOW (URLAddDialog), "gtk-add");
  gtk_window_set_type_hint (GTK_WINDOW (URLAddDialog), GDK_WINDOW_TYPE_HINT_DIALOG);

  dialog_vbox1 = GTK_DIALOG (URLAddDialog)->vbox;
  gtk_widget_set_name (dialog_vbox1, "dialog_vbox1");
  gtk_widget_show (dialog_vbox1);

  vbox8 = gtk_vbox_new (FALSE, 3);
  gtk_widget_set_name (vbox8, "vbox8");
  gtk_widget_show (vbox8);
  gtk_box_pack_start (GTK_BOX (dialog_vbox1), vbox8, FALSE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (vbox8), 6);

  urlLabel = gtk_label_new ("URL:");
  gtk_widget_set_name (urlLabel, "urlLabel");
  gtk_widget_show (urlLabel);
  gtk_box_pack_start (GTK_BOX (vbox8), urlLabel, FALSE, FALSE, 0);

  URLAddEntry = gtk_entry_new ();
  gtk_widget_set_name (URLAddEntry, "URLAddEntry");
  gtk_widget_show (URLAddEntry);
  gtk_box_pack_start (GTK_BOX (vbox8), URLAddEntry, TRUE, FALSE, 0);
  gtk_widget_set_size_request (URLAddEntry, 280, -1);
  gtk_tooltips_set_tip (tooltips, URLAddEntry, gettext("Type the URL of the stream."), NULL);
  gtk_entry_set_text (GTK_ENTRY (URLAddEntry), "http://");

  dialog_action_area1 = GTK_DIALOG (URLAddDialog)->action_area;
  gtk_widget_set_name (dialog_action_area1, "dialog_action_area1");
  gtk_widget_show (dialog_action_area1);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area1), GTK_BUTTONBOX_END);

  cancelbutton1 = gtk_button_new_from_stock ("gtk-cancel");
  gtk_widget_set_name (cancelbutton1, "cancelbutton1");
  gtk_widget_show (cancelbutton1);
  gtk_dialog_add_action_widget (GTK_DIALOG (URLAddDialog), cancelbutton1, GTK_RESPONSE_CANCEL);

  okbutton1 = gtk_button_new_from_stock ("gtk-ok");
  gtk_widget_set_name (okbutton1, "okbutton1");
  gtk_widget_show (okbutton1);
  gtk_dialog_add_action_widget (GTK_DIALOG (URLAddDialog), okbutton1, GTK_RESPONSE_OK);
  GTK_WIDGET_SET_FLAGS (okbutton1, GTK_CAN_DEFAULT);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (URLAddDialog, URLAddDialog, "URLAddDialog");
  GLADE_HOOKUP_OBJECT_NO_REF (URLAddDialog, dialog_vbox1, "dialog_vbox1");
  GLADE_HOOKUP_OBJECT (URLAddDialog, vbox8, "vbox8");
  GLADE_HOOKUP_OBJECT (URLAddDialog, urlLabel, "urlLabel");
  GLADE_HOOKUP_OBJECT (URLAddDialog, URLAddEntry, "URLAddEntry");
  GLADE_HOOKUP_OBJECT_NO_REF (URLAddDialog, dialog_action_area1, "dialog_action_area1");
  GLADE_HOOKUP_OBJECT (URLAddDialog, cancelbutton1, "cancelbutton1");
  GLADE_HOOKUP_OBJECT (URLAddDialog, okbutton1, "okbutton1");
  GLADE_HOOKUP_OBJECT_NO_REF (URLAddDialog, tooltips, "tooltips");

  gtk_widget_grab_default (okbutton1);
  return URLAddDialog;
}

GtkWidget*
create_FileSaveDialog (void)
{
  GtkWidget *FileSaveDialog;
  GtkWidget *dialog_vbox2;
  GtkWidget *dialog_action_area2;
  GtkWidget *button1;
  GtkWidget *button2;

  FileSaveDialog = gtk_file_chooser_dialog_new (gettext("Select a logfile"), NULL, GTK_FILE_CHOOSER_ACTION_SAVE, NULL);
  gtk_widget_set_name (FileSaveDialog, "FileSaveDialog");
  gtk_file_chooser_set_do_overwrite_confirmation (GTK_FILE_CHOOSER (FileSaveDialog), TRUE);
  /*
   * g_object_set (FileSaveDialog,
   *             "confirm", TRUE,
   *             NULL);
   */

  gtk_window_set_modal (GTK_WINDOW (FileSaveDialog), TRUE);
  gtk_window_set_type_hint (GTK_WINDOW (FileSaveDialog), GDK_WINDOW_TYPE_HINT_DIALOG);

  dialog_vbox2 = GTK_DIALOG (FileSaveDialog)->vbox;
  gtk_widget_set_name (dialog_vbox2, "dialog_vbox2");
  gtk_widget_show (dialog_vbox2);

  dialog_action_area2 = GTK_DIALOG (FileSaveDialog)->action_area;
  gtk_widget_set_name (dialog_action_area2, "dialog_action_area2");
  gtk_widget_show (dialog_action_area2);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area2), GTK_BUTTONBOX_END);

  button1 = gtk_button_new_from_stock ("gtk-cancel");
  gtk_widget_set_name (button1, "button1");
  gtk_widget_show (button1);
  gtk_dialog_add_action_widget (GTK_DIALOG (FileSaveDialog), button1, GTK_RESPONSE_CANCEL);
  GTK_WIDGET_SET_FLAGS (button1, GTK_CAN_DEFAULT);

  button2 = gtk_button_new_from_stock ("gtk-open");
  gtk_widget_set_name (button2, "button2");
  gtk_widget_show (button2);
  gtk_dialog_add_action_widget (GTK_DIALOG (FileSaveDialog), button2, GTK_RESPONSE_OK);
  GTK_WIDGET_SET_FLAGS (button2, GTK_CAN_DEFAULT);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (FileSaveDialog, FileSaveDialog, "FileSaveDialog");
  GLADE_HOOKUP_OBJECT_NO_REF (FileSaveDialog, dialog_vbox2, "dialog_vbox2");
  GLADE_HOOKUP_OBJECT_NO_REF (FileSaveDialog, dialog_action_area2, "dialog_action_area2");
  GLADE_HOOKUP_OBJECT (FileSaveDialog, button1, "button1");
  GLADE_HOOKUP_OBJECT (FileSaveDialog, button2, "button2");

  gtk_widget_grab_default (button2);
  return FileSaveDialog;
}

GtkWidget*
create_newConfirmDialog (void)
{
  GtkWidget *newConfirmDialog;
  GtkWidget *dialog_vbox3;
  GtkWidget *label18;
  GtkWidget *dialog_action_area3;
  GtkWidget *cancelbutton2;
  GtkWidget *okbutton2;

  newConfirmDialog = gtk_dialog_new ();
  gtk_widget_set_name (newConfirmDialog, "newConfirmDialog");
  gtk_window_set_title (GTK_WINDOW (newConfirmDialog), gettext("Confirm"));
  gtk_window_set_type_hint (GTK_WINDOW (newConfirmDialog), GDK_WINDOW_TYPE_HINT_DIALOG);

  dialog_vbox3 = GTK_DIALOG (newConfirmDialog)->vbox;
  gtk_widget_set_name (dialog_vbox3, "dialog_vbox3");
  gtk_widget_show (dialog_vbox3);

  label18 = gtk_label_new (gettext("Warning, using new will destroy all unsaved settings."));
  gtk_widget_set_name (label18, "label18");
  gtk_widget_show (label18);
  gtk_box_pack_start (GTK_BOX (dialog_vbox3), label18, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label18), GTK_JUSTIFY_CENTER);

  dialog_action_area3 = GTK_DIALOG (newConfirmDialog)->action_area;
  gtk_widget_set_name (dialog_action_area3, "dialog_action_area3");
  gtk_widget_show (dialog_action_area3);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area3), GTK_BUTTONBOX_END);

  cancelbutton2 = gtk_button_new_from_stock ("gtk-cancel");
  gtk_widget_set_name (cancelbutton2, "cancelbutton2");
  gtk_widget_show (cancelbutton2);
  gtk_dialog_add_action_widget (GTK_DIALOG (newConfirmDialog), cancelbutton2, GTK_RESPONSE_CANCEL);
  GTK_WIDGET_SET_FLAGS (cancelbutton2, GTK_CAN_DEFAULT);

  okbutton2 = gtk_button_new_from_stock ("gtk-ok");
  gtk_widget_set_name (okbutton2, "okbutton2");
  gtk_widget_show (okbutton2);
  gtk_dialog_add_action_widget (GTK_DIALOG (newConfirmDialog), okbutton2, GTK_RESPONSE_OK);
  GTK_WIDGET_SET_FLAGS (okbutton2, GTK_CAN_DEFAULT);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (newConfirmDialog, newConfirmDialog, "newConfirmDialog");
  GLADE_HOOKUP_OBJECT_NO_REF (newConfirmDialog, dialog_vbox3, "dialog_vbox3");
  GLADE_HOOKUP_OBJECT (newConfirmDialog, label18, "label18");
  GLADE_HOOKUP_OBJECT_NO_REF (newConfirmDialog, dialog_action_area3, "dialog_action_area3");
  GLADE_HOOKUP_OBJECT (newConfirmDialog, cancelbutton2, "cancelbutton2");
  GLADE_HOOKUP_OBJECT (newConfirmDialog, okbutton2, "okbutton2");

  return newConfirmDialog;
}

void cPigeGUIMessage(GtkWidget *mainWindow, gint type, gchar *message)
{
  GtkWidget *dialog;
  
  dialog = gtk_message_dialog_new(
      GTK_WINDOW(mainWindow),
      GTK_DIALOG_DESTROY_WITH_PARENT,
      type,
      GTK_BUTTONS_CLOSE,
      message
  );
  
  gtk_dialog_run(GTK_DIALOG(dialog));
  gtk_widget_destroy(GTK_WIDGET(dialog));
}

void InfoBox(GtkWidget *mainWindow, gchar *message)
{
  cPigeGUIMessage(mainWindow, GTK_MESSAGE_INFO, message);
}

void ErrorBox(GtkWidget *mainWindow, gchar *message)
{
  cPigeGUIMessage(mainWindow, GTK_MESSAGE_ERROR, message);
}

void WarningBox(GtkWidget *mainWindow, gchar *message)
{
  cPigeGUIMessage(mainWindow, GTK_MESSAGE_WARNING, message);
}
